# Generated by Django 2.1.2 on 2018-11-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_remove_parking_id_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='total_places',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
