# Generated by Django 2.1.2 on 2018-11-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20181122_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='device_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='total_places',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
