# Generated by Django 2.1.2 on 2018-11-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20181122_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='device_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
