# Generated by Django 2.1.2 on 2018-11-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20181122_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='total_places',
        ),
    ]
